[tools]
usage = "latest"
node = "latest"
bun = "latest"
fzf = "latest"
zoxide = "latest"
"npm:@antfu/ni" = "latest"
lazygit = "latest"
oxlint = "latest"
oxfmt = "latest"
"github:anomalyco/opencode" = "latest"
rust = "latest"
"cargo:fd-find" = "latest"
"cargo:bat" = "latest"
"cargo:eza" = "latest"
"cargo:du-dust" = "latest"
"cargo:ripgrep" = "latest"
"cargo:tokei" = "latest"
"cargo:bottom" = "latest"
"cargo:tealdeer" = "latest"
"cargo:git-delta" = "latest"
go = "latest"
"github:cli/cli" = "latest"
"cargo:starship" = "latest"
gcloud = "latest"
python = "latest"
"github:backnotprop/plannotator" = "latest"
"github:gittower/git-flow-next" = { version = "latest", rename_exe = "git-flow" }
cargo-binstall = "latest"
