[tools]
node = "latest"
bun = "latest"
vp = "latest"
pnpm = "latest"
usage = "latest"
fzf = "latest"
zoxide = "latest"
"npm:@antfu/ni" = "latest"
lazygit = "latest"
oxlint = "latest"
oxfmt = "latest"
rust = "latest"
cargo-binstall = "latest"
bat = "latest"
eza = "latest"
dust = "latest"
fd = "latest"
ripgrep = "latest"
tokei = "latest"
bottom = "latest"
tealdeer = "latest"
delta = "latest"
starship = "latest"
go = "latest"
gcloud = "latest"
python = "latest"
"github:cli/cli" = "latest"
"github:gittower/git-flow-next" = { version = "latest", rename_exe = "git-flow" }
ffmpeg = "latest"
yt-dlp = { version = "latest", rename_exe = "yt-dlp" }
codex = "latest"
"npm:command-code" = "latest"
jq = "latest"

[settings]
cargo.binstall = true
