[plugins]
cursor-agent = "https://github.com/icholy/asdf-cursor-agent"

[tools]
node = "latest"
bun = "latest"
vp = "latest"
pnpm = "latest"
usage = "latest"
fzf = "latest"
zoxide = "latest"
"npm:@antfu/ni" = "latest"
lazygit = "latest"
oxlint = "latest"
oxfmt = "latest"
rust = "latest"
cargo-binstall = "latest"
"cargo:fd-find" = "latest"
"cargo:bat" = "latest"
"cargo:eza" = "latest"
"cargo:du-dust" = "latest"
"cargo:ripgrep" = "latest"
"cargo:tokei" = "latest"
"cargo:bottom" = "latest"
"cargo:tealdeer" = "latest"
"cargo:git-delta" = "latest"
"cargo:starship" = "latest"
go = "latest"
gcloud = "latest"
python = "latest"
"github:cli/cli" = "latest"
"github:backnotprop/plannotator" = "latest"
"github:gittower/git-flow-next" = { version = "latest", rename_exe = "git-flow" }
ffmpeg = "latest"
yt-dlp = { version = "latest", rename_exe = "yt-dlp" }
cursor-agent = "latest"
